version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y curl
      - curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - sudo mv /tmp/eksctl /usr/local/bin
      - eksctl version   # Verify eksctl installation
      - curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
      - sudo apt-get install apt-transport-https --yes
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
      - sudo apt-get update
      - sudo apt-get install helm
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region us-east-1

  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t currency-converter .
      - echo Tagging the Docker image...
      - docker tag currency-converter:latest 135504386187.dkr.ecr.us-east-1.amazonaws.com/currency-converter:latest
      - echo Pushing the Docker image to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 135504386187.dkr.ecr.us-east-1.amazonaws.com
      - docker push 135504386187.dkr.ecr.us-east-1.amazonaws.com/currency-converter:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - export KUBECONFIG=/root/.kube/config  # Explicitly set KUBECONFIG
      - aws eks update-kubeconfig --region us-east-1 --name currency-converter-cluster
      - cat /root/.kube/config  # Check the content of kubeconfig
      - kubectl get nodes  # Verify kubectl can access the cluster
      - kubectl config view  # Verify the kubeconfig context
      - kubectl config current-context  # Ensure the correct context is set
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm repo update
      - helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
        --namespace ingress-nginx --create-namespace \
        --set controller.kind=DaemonSet \
        --set controller.hostPort.enabled=true \
        --set controller.ingressClass=nginx
      - kubectl get pods -n ingress-nginx
      - helm upgrade --install currency-converter ./helm/currency-converter --set image.repository=135504386187.dkr.ecr.us-east-1.amazonaws.com/currency-converter,image.tag=latest

artifacts:
  files:
    - '**/*'

