version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running tests
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      - docker build -t currency-converter .
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 135504386187.dkr.ecr.us-east-1.amazonaws.com
      - echo Tagging the Docker image...
      - docker tag currency-converter:latest 135504386187.dkr.ecr.us-east-1.amazonaws.com/currency-converter:latest
      - echo Pushing the Docker image...
      - docker push 135504386187.dkr.ecr.us-east-1.amazonaws.com/currency-converter:latest
