version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum remove -y curl --skip-broken

  build:
    commands:
      - echo "Build phase"

  post_build:
    commands:
      - sudo yum install -y curl
      - curl --version
