# values.yaml

replicaCount: 1

image:
  repository: 135504386187.dkr.ecr.us-east-1.amazonaws.com/currency-converter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5555

ingress:
  enabled: true
  host: jo-mab.com

secret:
  apikey: ZGEwODEyMmYwZW1zaGViMjU5YWJlOGZhMTUxZHAxYjkzN2Zqc243YTExMGYzZDA4OWU=