# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: APIKEY
        - name: APIHOST
          value: "currency-conversion-and-exchange-rates.p.rapidapi.com"

