# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: currency-converter
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}

